### ISSUE TITLE
No proper answer from MCU

### ISSUE THREAD

**Issue by jorgegarciadev** [4refr0nt/luatool#11]
I'm trying to upload a file to my ESP8266 with nodeMCU 0.9.5 (build 20150213) and luatool raises ```No proper answer from MCU```.  I can connect to the ESP8266 via Stino's serial monitor and screen command. Any idea about what is happening?

**Comment by marcoskirsch** [comment]
Did you connect gpio0 to ground?

**Comment by jorgegarciadev** [comment]
I have tried both, with and without connecting gpio0, and in both cases I get the same exception.

**Comment by 4refr0nt** [comment]
1. Reflash latest NodeMCU dev https://github.com/nodemcu/nodemcu-firmware/releases/tag/dev20150311
2. Try ESPlorer http://esp8266.ru/esplorer/ and see logs

**Comment by jorgegarciadev** [comment]
The problem was my setup, I'm using an Arduino Due with SoftwareSerial to comunicate with the ESP8266. Luatool connecting was faster than Arduino creating the Serial connection, so making sleep the script for a couple of seconds fixed the problem. Sorry for opening an issue for something that stupid.

**Comment by mchuman** [comment]
I took me hours for the solution of this problem. Sometimes i could upload things, sometimes not ... i reflashed the firmware and it works one or 2 times and then not anymore .... then i discovered the problem:

if you use programs like picocom or other programs communicating with over serial port with your ESP8266, you cant upload files or communicate with other programs e.g luatool at the same time!
So close your picocom (or other tools) connection and make sure, luatool is the only software communicating with the ESP8266 at this time.

I hope i could beware somebody before freaking out like me :P
